# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- azure-pipelines

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: build
  jobs:
    - job: build
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 5'
        inputs:
          version: 5.x
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: '**/*.sln'
      
      - task: PowerShell@2
        #displayName: "Set Hidi's version-number"
        name: setCurrProjVersion
        inputs:
          targetType: 'inline'
          script: |
            $xml = [Xml] (Get-Content .\src\Microsoft.OpenApi.Hidi\Microsoft.OpenApi.Hidi.csproj)
            $version = $xml.Project.PropertyGroup.Version
            echo $version
            echo "##vso[task.setvariable variable=version; isOutput=true]$version"
            
      - task: MSBuild@1
        displayName: 'Pack OpenApi Hidi'
        inputs:
          solution: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
          configuration: Release
          msbuildArguments: '/t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/Nugets /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          arguments: -c Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true --output $(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version) -p:PublishTrimmed=true
          projects: 'src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj'
          publishWebProjects: False
          zipAfterPublish: false

      - task: PublishBuildArtifacts@1
        displayName: 'Package Hidi'
        inputs: 
          ArtifactName: Nugets  
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Nugets'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Hidi'
        inputs: 
          ArtifactName: Microsoft.OpenApi.Hidi-v$(version)  
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version)'
     
- stage: deploy
  # condition: and(contains(variables['build.sourceBranch'], 'refs/heads/vnext'), succeeded())
  dependsOn: build
  jobs:
    - deployment: deploy
      dependsOn: []
      environment: none
      strategy:
        runOnce:
          deploy:
            pool:
              vmImage: ubuntu-latest
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: Download hidi executable from artifacts
              inputs:
                source: current
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  $artifactName = Get-ChildItem -Path $(Pipeline.Workspace) -Filter Microsoft.OpenApi.Hidi-* -recurse | select -First 1
                  $artifactVersion= $artifactName -replace "Microsoft.OpenApi.Hidi-", ""                  
                  #Set Variable $artifactName and $artifactVersion
                  Write-Host "##vso[task.setvariable variable=artifactVersion; isSecret=false; isOutput=true]$artifactVersion"
                  Write-Host "##vso[task.setvariable variable=artifactName; isSecret=false; isOutput=true]$artifactName.FullName"
              displayName: 'Fetch Artifact Name'

            - task: GitHubRelease@1
              displayName: 'GitHub release (create)'
              inputs:
                gitHubConnection: 'Github-MaggieKimani1'
                tagSource: userSpecifiedTag
                tag: '$(artifactVersion)'
                title: '$(artifactName)'
                releaseNotesSource: inline
                assets: '$(Pipeline.Workspace)\**\*.exe'
                changeLogType: issueBased