# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
  - msbuild
  - vstest

steps:
- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    configuration: Release
- task: VSTest@2
  displayName: 'XUnit Tests'
  inputs:
    testAssemblyVer2: |
     **\*.Tests.dll

    vsTestVersion: 16.0
    codeCoverageEnabled: true

- task: MSBuild@1
  displayName: 'Pack OpenApi Hidi'
  inputs:
    solution: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
    configuration: Release
    msbuildArguments: '/t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory) /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Nugets'
  inputs:
    ArtifactName: Nugets

- task: GitHubRelease@1
  displayName: 'GitHub release (edit)'
  condition: succeededOrFailed()
  inputs:
    gitHubConnection: 'Github-MaggieKimani1'
    action: edit
    tagSource: userSpecifiedTag
    tag: '$(artifactVersion)'
    title: '$(artifactVersion)'
    releaseNotesSource: inline
    assets: '$(Pipeline.Workspace)\*.nupkg'
    changeLogType: issueBased
    changeLogLabels: '[{ "label" : "bug", "displayName" : "Bugs", "state" : "closed" }]'
